FROM registry.access.redhat.com/ubi8/python-39
MAINTAINER Pablo Orviz <orviz@ifca.unican.es>

RUN apt-get update \
    && apt-get install -y openjdk-11-jdk-headless

# Hack to use the same user/group ID in the container
# and in Jenkins (otherwise we get random perms issues)
RUN mkdir /home/jenkins
RUN groupadd -g 1000 jenkins
RUN useradd -r -u 1000 -g jenkins -d /home/jenkins jenkins
RUN chown jenkins:jenkins /home/jenkins
USER jenkins
WORKDIR /home/jenkins

CMD ["/bin/bash"]
